### ISSUE TITLE
[bug] Dashboard shows empty open Request bucket!

### ISSUE THREAD

**Issue by LeoKotschenreuther** [hpi-swt2/event-und-raumplanung#341] opened 2015-02-02 15:00 UTC
The following errors occur:
- I logged in as user with the right to approve events but I don't see any events in the "Events approve" widged on the dashboard.
- As user without the right to approve events I see the widget although I'm not allowed to approve events.
- The link to "Show all" links to the event view and not the approval view.

**Comment by rosabraatz** [comment] 2015-02-03 10:16
Wer hat denn das Widget gemacht? Vielleicht wäre es einfacher, wenn sich die Gruppe das mal anschaut? Wir hatten bisher noch nichts damit zu tun ...

**Comment by LeoKotschenreuther** [comment] 2015-02-03 10:40
@Atyanar @lulufaber @DasDingGehtNicht Wisst ihr wer das Widget gemacht hat?

**Comment by SvenLehmann** [comment] 2015-02-03 15:19
should be fixed with latest commit on Dolphins

1. is not a bug since it only shows that the user has the ability to approve events (same as with the link in the header)
2. has been fixed
3. has been fixed as well

**Closed** 2015-02-06 08:55 UTC
Labels: bug
